/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jsageImport.view;

import javax.swing.JOptionPane;
import jsageImport.controler.ControlerFuncionarioNG;
import jsageImport.exception.JsageImportException;


/**
 *
 * @author Gustavo
 */
public class TestaConexao extends javax.swing.JInternalFrame {

    /**
     * Creates new form TestaConexao
     */
    public TestaConexao() {
        initComponents();
        jlStatus.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlServidor = new javax.swing.JLabel();
        jlBanco = new javax.swing.JLabel();
        jlPorta = new javax.swing.JLabel();
        jlUsuario = new javax.swing.JLabel();
        jlSenha = new javax.swing.JLabel();
        jtfServidor = new javax.swing.JTextField();
        jtfBanco = new javax.swing.JTextField();
        jtfPorta = new javax.swing.JTextField();
        jtfUsuario = new javax.swing.JTextField();
        jpSenha = new javax.swing.JPasswordField();
        jbConectar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jlStatus = new javax.swing.JLabel();
        jlResultado = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Teste de Conexão");

        jlServidor.setText("IP Servidor");

        jlBanco.setText("Banco");

        jlPorta.setText("Porta");

        jlUsuario.setText("Usuário");

        jlSenha.setText("Senha");

        jbConectar.setText("Conectar");
        jbConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConectarActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jlStatus.setText("Status");

        jlResultado.setText("Status:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlServidor)
                    .addComponent(jlBanco)
                    .addComponent(jlPorta)
                    .addComponent(jlUsuario)
                    .addComponent(jlSenha)
                    .addComponent(jlResultado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlStatus)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbConectar)
                        .addGap(37, 37, 37)
                        .addComponent(jbCancelar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jtfServidor)
                        .addComponent(jtfBanco, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                        .addComponent(jtfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlServidor)
                    .addComponent(jtfServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlBanco)
                    .addComponent(jtfBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPorta)
                    .addComponent(jtfPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlUsuario)
                    .addComponent(jtfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSenha)
                    .addComponent(jpSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlStatus)
                    .addComponent(jlResultado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbConectar)
                    .addComponent(jbCancelar))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConectarActionPerformed
        ControlerFuncionarioNG control = new ControlerFuncionarioNG();
        try {
           if (jtfServidor.getText().equals("")||jtfBanco.getText().equals("")||jtfPorta.getText().equals("")||jtfUsuario.getText().equals("")||jpSenha.getText().equals("")){
               throw new JsageImportException("Todos os campos precisam ser preenchidos!");               
           }else {
               //jlStatus.setText(control.testarConexao(jtfServidor.getText(), jtfBanco.getText(), jtfPorta.getText(), jtfUsuario.getText(), jpSenha.getText()));           
               jlStatus.setVisible(true);
           }
        } catch (JsageImportException ex) {
            System.out.println("Erro na execução do Teste: " + ex);
        }
    }//GEN-LAST:event_jbConectarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbConectar;
    private javax.swing.JLabel jlBanco;
    private javax.swing.JLabel jlPorta;
    private javax.swing.JLabel jlResultado;
    private javax.swing.JLabel jlSenha;
    private javax.swing.JLabel jlServidor;
    private javax.swing.JLabel jlStatus;
    private javax.swing.JLabel jlUsuario;
    private javax.swing.JPasswordField jpSenha;
    private javax.swing.JTextField jtfBanco;
    private javax.swing.JTextField jtfPorta;
    private javax.swing.JTextField jtfServidor;
    private javax.swing.JTextField jtfUsuario;
    // End of variables declaration//GEN-END:variables
}
